version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    image: it-essega
    container_name: it-essega
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    depends_on:
      - mysql
    networks:
      laravel:
        driver: bridge

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: apa_je_nanti
      MYSQL_DATABASE: it-essega
      MYSQL_USER: apa_je_nanti
      MYSQL_PASSWORD: apa_je_nanti
    volumes:
      - mysql-data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      laravel:
        driver: bridge

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      laravel:
        driver: bridge
volumes:
  mysql-data:


networks:
  laravel:
    driver: bridge
